- hosts: fuse_messaging
  remote_user: root

  roles:
    - update
    - qpid_tools
    - tools

#   - epel                      # centos only
    - geerlingguy.repo-epel     # rhel; need to execute beforehand:  sudo ansible-galaxy install geerlingguy.repo-epel

    - yum-clean
    - reboot
    - guest-additions
    - useradd
    - mate
    - selinux
    - firewalld
    - java
    - maven
    - oc
    - openldap
    - yum-clean
    - jxplorer
    - amq
