apiVersion: v1
kind: Route
metadata:
  labels:
    application: broker
    template: amq6-persistent
  name: broker-amq-tcp-ssl
spec:
  host: broker-amq-tcp-ssl-projectname.mwl.opentlc.com
  port:
    targetPort: "61617"
  tls:
    termination: passthrough
  to:
    kind: Service
    name: broker-amq-tcp-ssl
status: {}

